project:
  type: website
  resources:
    - "data/*"
  output-dir: _site

website:
  title: "Kaia Quigg"
  navbar:
    background: primary
    search: false
    left:
      - href: index.qmd
        text: Home
      - href: ecommerce-sql-analysis.qmd
        text: "SQL Analytics"
      - href: crablobby.qmd
        text: "Predictive Modeling"
      - href: ecolobby.qmd
        text: "Sustainability BI"

format:
  html:
    theme: flatly
    toc: true